### ISSUE TITLE
domain name of a server running AdGuard Home leaked

### ISSUE THREAD

**Issue by jaodei** [jpgpi250/piholemanual#20]
Hi there,

I have a server running AdGuard Home leaked. I see its domain name is listed at https://github.com/jpgpi250/piholemanual/blob/master/DOH.rpz.

May I know how you obtain this list? I do not want to publize its server name to limit the users to only myself. 

Cheers.

**Comment by jpgpi250** [comment]
The list is compiled, using various lists found on the web, see [here](https://jpgpi250.github.io/piholemanual/doc/Block%20DOH%20with%20pfsense.pdf). Since you don't specify the domain name, I can't tell you which list provides the entry.

Once you register a domain, it probably can be found on the "newly registered domains" lists, see [here](https://github.com/PeterDaveHello/nrd-list-downloader) (GitHub), but there are plenty of other ways to find domains / IP addresses / services, that are accessible from the internet. Once a service is accessible from the internet, it will be found, sooner or later.
