### ISSUE TITLE
issue with one DoHProxy

### ISSUE THREAD

**Issue by NazgulCoder** [jpgpi250/piholemanual#24]
Hi,

thank you for your great list first of all, however I want to flag something

151.139.128.10

this IP is not a DoH server but a CDN/Reverse proxy used by many websites. Ergo, if you implement it in your firewall list it will block multiple legit websites.

Thank you for your attention :)

**Comment by jpgpi250** [comment]
duplicate, see https://github.com/jpgpi250/piholemanual/issues/23

151.139.128.10 is the address returned for the following domains:
- dns-secondary.cloudnx.cloud
- q3i6k7j3.stackpathcdn.com

dns-secondary.cloudnx.cloud appears in the following lists
- https://raw.githubusercontent.com/wiki/curl/curl/DNS-over-HTTPS.md
- https://raw.githubusercontent.com/jbaggs/doh-intel/master/doh.intel
- https://raw.githubusercontent.com/beamrod/doh_hostlist/main/host_list.txt

q3i6k7j3.stackpathcdn.com appears in the following lists
- https://raw.githubusercontent.com/wiki/curl/curl/DNS-over-HTTPS.md
- https://raw.githubusercontent.com/jbaggs/doh-intel/master/doh.intel

I'don't add domains myself, I consolidate entries from various lists, ref the [manual](https://jpgpi250.github.io/piholemanual/doc/Block%20DOH%20with%20pfsense.pdf).

as explained in an earlier [issue](https://github.com/jpgpi250/piholemanual/issues/23), you'll need to create a CDIR (network) exception (151.139.128.0/24) in order to whitelist these addresses. This is explained in section 10 (CIDR (network) Exceptions) of the [manual](https://jpgpi250.github.io/piholemanual/doc/Block%20DOH%20with%20pfsense.pdf).

**Comment by NazgulCoder** [comment]
Ok gotcha, thank you for the fast response, I'll whitelist it manually when importing in my PHP script
