### ISSUE TITLE
[bug]: The DoH domain blocklist contains DNSCrypt-only provider domains.

### ISSUE THREAD

**Issue by T145** [jpgpi250/piholemanual#34]
DNSCrypt is its own protocol and doesn't need TCP to function. Therefore any DNSCrypt providers should be removed from the DoH blocklists.

**Comment by jpgpi250** [comment]
The URL to retrieve the dnscrypt public resolvers is https://download.dnscrypt.info/dnscrypt-resolvers/json/public-resolvers.json. This json file contains a field "**proto**", if the content is "**DoH**", the entry is considered a DoH provider, thus added to the list.

dnscrypt can use a proprietary protocol ("proto"="DNSCrypt"), but it can also be configured to use DoH, DoT, DoQ.

Since the goal is to block DoH, the entries will not be removed. You can always configure exceptions, in order to allow a specific entry, see the [manual](https://jpgpi250.github.io/piholemanual/doc/Block%20DOH%20with%20pfsense.pdf). It's highly recommended to use [response policy zones](https://jpgpi250.github.io/piholemanual/doc/Unbound%20response%20policy%20zones.pdf), when configuring exceptions.

**Comment by T145** [comment]
No, it cannot be configured to use DoH, DoT, or DoQ. DNSCrypt is its own protocol and doesn't work on top of TLS or HTTPS. You can configure a service to respond to these protocols in tandem (like with [Tiarap](https://doh.tiar.app/)), but the protocols themselves are independent. The list you're referencing includes both DoH and DNSCrypt providers (https://dnscrypt.info/public-servers), so you're liking assuming because the official page lists them together then they must be related.

To my earlier point, if there's a service being used to handle both DoH and DNSCrypt I'm all for it being blocked. In other words if the same host handles both services then slap it down. But in your DoH RPZ you have included the following resolvers:
```
2.dnscrypt-cert.blahdns.com
2.dnscrypt-cert.browser.yandex.net
2.dnscrypt-cert.captnemo.in
2.dnscrypt-cert.dns.seby.io
2.dnscrypt-cert.ffmuc.net
2.dnscrypt-cert.opendns.com
2.dnscrypt-cert.oszx.co
2.dnscrypt-cert.quad9.net
2.dnscrypt-cert.shield-2.dnsbycomodo.com
```
Which are 1) not listed in the DNSCrypt public resolvers, and 2) are explicit DNSCrypt certificate providers. They should not be included in the DoH list.

**Comment by jpgpi250** [comment]
see sql query results below, the urllist_id field indicates the list(s) the domains have been extracted from.

3: https://raw.githubusercontent.com/oneoffdallas/dohservers/master/list.txt
13: https://raw.githubusercontent.com/crypt0rr/public-doh-servers/main/dns.list
20: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/doh.txt
22: https://raw.githubusercontent.com/akrauze/doh-serverlist-4-pihole/main/list.txt
23: https://raw.githubusercontent.com/jsimonetti/public_doh_servers/main/doh_server_domains.list

![image](https://github.com/jpgpi250/piholemanual/assets/24669386/9a489cc8-5583-488a-86fb-d86a933bfc47)

I don't create the lists, I only consolidate the results. If the domains are removed from the source lists, they will disappear from the consolidated result.

**Comment by jpgpi250** [comment]
closed after 21 days without response
