### ISSUE TITLE
Missing files DOHexceptionsIPv4.txt & v6.txt

### ISSUE THREAD

**Issue by sbytnar** [jpgpi250/piholemanual#43]
"To overcome this, two additional lists (DOHexceptionsIPv4.txt and
DOHexceptionsIPv6.txt) are provided."
https://raw.githubusercontent.com/jpgpi250/piholemanual/master/DOHexceptionsIPv4.txt
https://raw.githubusercontent.com/jpgpi250/piholemanual/master/DOHexceptionsIPv6.txt

**Comment by jpgpi250** [comment]
As discussed in this [issue](https://github.com/jpgpi250/piholemanual/issues/17), creating and maintaining the exceptionfiles is the responsibility of the user, they are no longer provided, due to regional differences and different needs for specific users.

I've checked the latest version of the [manual](https://jpgpi250.github.io/piholemanual/doc/Block%20DOH%20with%20pfsense.pdf), the quote you provided isn't in there. Old version of the manual?

**Comment by jpgpi250** [comment]
closed after 21 days without response
