### ISSUE TITLE
www.liveleak.com not working

### ISSUE THREAD

**Issue by pcdiks** [jpgpi250/piholemanual#5]
The site www.liveleak.com is not working properly.
This ip is blocked that causes the problem: 104.16.133.229

Could you solve this?

**Comment by jpgpi250** [comment]
Nothing to fix here, the IP (104.16.133.229) and the IPv6 equivalent are already in the exceptions list.
I warned in all my posts that you need to make exception rules, using the exception files for specific devices, clearly, if you created these rules, they aren't working.
There is currently only one DNS entry that requires an exception (dns.cloudflare.com), because they host regular DNS (port 53), DoH (port 443) and content (cdnjs.cloudflare.com) behind the same IP address.

Don't know about the exception rules? read [here](http://users.telenet.be/MySQLplaylist/blockDOH.pdf).

**Comment by pcdiks** [comment]
Yes, I have implemented the exceptions and after disabling the rules to block DoH the site still does not work so it’s something else. 
I do think your exception rules are not correct. In your pdf you show that the source must be an ip on the block list and the target must be the exception. Traffic on the lan interface can never have a source ip that is not on the lan. If you remove the source or change the source to lan net you have a rule that is technically correct.

**Comment by jpgpi250** [comment]
www.liveleak.com works perfectly in my environment, with the rules, described in the pdf. I can see in the logs, the exception rule is trigered (dns.cloudflare.com points to both 104.16.133.229 and 104.16.132.229

![image](https://user-images.githubusercontent.com/24669386/87784082-ef30dc00-c835-11ea-88e5-615cdce29a31.png)

quote
In your pdf you show that the **source** must be an ip on the block list and the **target** must be the exception.
/quote

_the source must be an ip on the block list_ This is wrong!

In the **block** rules, the **source** is any, the **target** is the block list
In the exception (**allow**) rules, the **source** is the **alias used to define your devices that require an exception**, the **target** is the exception list

The IP, used in the pdf (pfsense configuration / defining the exception alias ) is an example. I assume this is obvious, you need to enter your own IP addres(es)

check your rules again...
